version: '3.8'

services:
  web:
    build:
      context: ../
      dockerfile: ./docker/backend.dockerfile
    image: annotaid/backend.dev
    ports:
      - 8000:8000
    env_file:
      - ../.env
    depends_on:
      - redis
      - celery_worker
      - postgis

  redis:
    image: redis:alpine3.18
    ports:
      - 6379:6379

  celery_worker:
    build:
      context: ../
      dockerfile: ./docker/worker.dockerfile
    image: annotaid/worker.dev
    env_file:
      - ../.env
    depends_on:
      - redis
      - postgis
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  postgis:
    image: postgis/postgis:16-master
    env_file:
      - ../.env
    ports:
      - 5432:5432
    volumes:
      - postgis_data:/var/lib/postgresql/data

volumes:
  postgis_data:
