services:
  web:
    image: annotaid/backend:main
    build: !reset null
    restart: always
    healthcheck:
      test: wget --no-verbose -O /dev/null --tries=1 http://localhost:8080/ || exit 1
      interval: 1s
      timeout: 5s
    depends_on:
      - redis
      - celery_worker
      - postgis
    networks:
      - annotaid-be

  redis:
    image: redis:alpine3.18
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - annotaid-be

  celery_worker:
    image: annotaid/worker:main
    build: !reset null
    restart: always
    depends_on:
      - redis
      - postgis
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - annotaid-be

  postgis:
    image: postgis/postgis:16-master
    env_file:
      - ../.env
    ports:
      - 5432:5432
    volumes:
      - postgis_data:/var/lib/postgresql/data
    networks:
      - annotaid-be

networks:
  annotaid-be:

volumes:
  postgis_data:
