version: '3.8'

services:
  web:
    build:
      context: ../
      dockerfile: ./docker/backend.dockerfile
    image: annotaid/backend.dev
    ports:
      - 8000:8000
    env_file:
      - ../.env
    depends_on:
      - redis
      - celery_worker

  redis:
    image: redis:alpine3.18
    ports:
      - 6379:6379

  celery_worker:
    build:
      context: ../
      dockerfile: ./docker/worker.dockerfile
    image: annotaid/worker.dev
    env_file:
      - ../.env
    depends_on:
      - redis
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
