version: '3.8'

services:
  redis:
    container_name: redis
    image: redis:alpine3.18
    restart: on-failure
    ports:
      - 6379:6379
  postgis:
    container_name: postgis
    image: postgis/postgis:16-master
    restart: on-failure
    env_file:
      - ../.env
    ports:
      - 5432:5432
    volumes:
      - postgis_data:/var/lib/postgresql/data
  reader:
    container_name: reader
    image: annotaid/reader:latest
    restart: on-failure
    env_file:
      - ../.env
    ports:
      - 9000:9000
    volumes:
      - type: bind
        source: $READER_SOURCE_DATA
        target: $READER_TARGET_DATA
      - type: bind
        source: $READER_MEM_SOURCE
        target: $READER_MEM_TARGET

volumes:
  postgis_data:
