name: Build and Release

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install @semantic-release/git @semantic-release/changelog -D

      - name: Semantic release
        run: npx semantic-release@22
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}