name: Build and Release

on:
  push:
    branches: [main]

env:
  POETRY_VERSION: 1.8.2

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    concurrency: push
    outputs:
      released: ${{ steps.release.outputs.released }}
      tag: ${{ steps.release.outputs.tag }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Semantic release
        id: release
        run: |
          pip install python-semantic-release

          git config --global user.name "release-bot"
          git config --global user.email "github-actions@github.com"

          semantic-release version
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

  docker_backend:
    needs: [release]
    if: needs.release.outputs.released == 'true'
    name: "Build and push backend docker image"
    uses: ./.github/workflows/docker.yaml
    with:
      dockerfile: ./docker/backend.dockerfile
      image_name: backend
      tag: ${{ needs.release.outputs.tag }}
    secrets: inherit

  docker_worker:
    needs: [release]
    if: needs.release.outputs.released == 'true'
    name: "Build and push worker docker image"
    uses: ./.github/workflows/docker.yaml
    with:
      dockerfile: ./docker/worker.dockerfile
      image_name: worker
      tag: ${{ needs.release.outputs.tag }}
    secrets: inherit
